# Generated by Django 6.0.2 on 2026-02-14 02:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Guest', max_length=100)),
                ('email', models.EmailField(default='guest@example.com', max_length=254)),
                ('phone', models.CharField(default='0000000000', max_length=20)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('suite', 'Suite')], default='single', max_length=20)),
                ('check_in', models.DateField(default=datetime.date.today)),
                ('check_out', models.DateField(default=datetime.date.today)),
                ('nationality', models.FileField(default='defaults/placeholder.pdf', upload_to='id_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
