# Generated by Django 6.0.2 on 2026-02-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='nationality',
            field=models.FileField(default='defaults/placeholder.pdf', max_length=200, upload_to='id_proofs/'),
        ),
    ]
