# Generated by Django 6.0.2 on 2026-02-18 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=datetime.date(2026, 2, 19)),
        ),
    ]
